import os
import re
import pandas as pd

# Path to the root where fold directories are stored. The ckpt folder generated by /segmentation/run.py (detect phase)
ROOT_DIR = "path/to/new_ckpt/detect/itunet_d24"

# Pattern to extract metrics from filenames
pattern = re.compile(
    r"val_auroc:(\d+\.\d+)-val_ap:(\d+\.\d+)-val_score:(\d+\.\d+)\.pth"
)

summary = []

# Loop through each fold directory
for fold in sorted(os.listdir(ROOT_DIR)):
    fold_path = os.path.join(ROOT_DIR, fold)
    if not os.path.isdir(fold_path):
        continue

    best_metrics = {'val_score': -1.0, 'val_ap': 0.0, 'val_auroc': 0.0}
    best_file = ""

    for file in os.listdir(fold_path):
        match = pattern.search(file)
        if match:
            auroc, ap, score = map(float, match.groups())
            if score > best_metrics['val_score']:
                best_metrics.update({
                    'val_score': score,
                    'val_ap': ap,
                    'val_auroc': auroc
                })
                best_file = file

    if best_file:
        summary.append({
            'fold': fold,
            'best_checkpoint': best_file,
            'val_score': best_metrics['val_score'],
            'val_ap': best_metrics['val_ap'],
            'val_auroc': best_metrics['val_auroc']
        })

# Convert to DataFrame and print
df = pd.DataFrame(summary)
print(df)

# Optional: save to CSV
output_csv = os.path.join(ROOT_DIR, "fold_metrics_summary.csv")
df.to_csv(output_csv, index=False)
print(f"\nSaved summary to: {output_csv}")

print("\n=== Cross-Fold Summary ===")
print("Mean ± Std")
for metric in ['val_score', 'val_ap', 'val_auroc']:
    mean = df[metric].mean()
    std = df[metric].std()
    print(f"{metric}: {mean:.5f} ± {std:.5f}")
